### ISSUE TITLE
Fix the setup-users script. 

### ISSUE THREAD

**Issue by tnscorcoran** [odh-labs/ml-workshop#3]
Fix the setup-users script. As discussed in 'Adding users to the workshop' in the setup: https://github.com/odh-labs/ml-workshop/blob/main/docs/setup.md

Scripts are here
https://github.com/odh-labs/ml-workshop/tree/main/src/deploy/scripts

Running it shouldn't destroy opentlc-mgr - like Tom's setup does :-)

**Comment by bryonbaker** [comment]
@tnscorcoran - this is fixed now isn't it?

**Comment by tnscorcoran** [comment]
@bryonbaker I think so
 Seems Faisal fixed it the next day
